server:
   port: 8090
   servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:cachedb;DB_CLOSE_DELAY=-1;MODE=Oracle
    #url: jdbc:h2:file:~/cachedb;DB_CLOSE_DELAY=-1;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init.schema-locations: classpath:schema_h2.sql
    init.data-locations:   classpath:data_h2.sql
  jpa:
    hibernate:
      ddl-auto: none           # we’ll feed schema.sql ourselves
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints.web.exposure.include: health
#  endpoints.web.base-path: /api/actuator
